using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventEase.Models;

// Represents a booking linking an event to a venue
public partial class Booking // Model generated by Scaffolding
{
    [Key]
    public int BookingId { get; set; }

    public int EventId { get; set; } // Linked event ID

    public int VenueId { get; set; } // Linked venue ID

    [Column(TypeName = "datetime")]
    public DateTime BookingDate { get; set; } 

    [ForeignKey("EventId")]
    [InverseProperty("Bookings")]
    public virtual Event Event { get; set; } = null!; 
    [ForeignKey("VenueId")]
    [InverseProperty("Bookings")]
    public virtual Venue Venue { get; set; } = null!; 
}
