using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventEase.Models;

public partial class Event // Model Generated by scaffolding
{
    [Key]
    public int EventId { get; set; } 

    [StringLength(100)]
    [Unicode(false)]
    public string EventName { get; set; } = null!; 

    [Column(TypeName = "text")]
    public string Description { get; set; } = null!; 
    [Column(TypeName = "datetime")]
    public DateTime EventDate { get; set; } 

    [Column(TypeName = "text")]
    public string ImageUrl { get; set; } = null!; 
    [InverseProperty("Event")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>(); // Bookings linked to this event
}

