using System;
using System.Collections.Generic;
using EventEase.Models;
using Microsoft.EntityFrameworkCore;

namespace EventEase.Data;

public partial class ApplicationDbContext : DbContext
{
    // Default constructor (generated by scaffolding)
    public ApplicationDbContext()
    {
    }

    // Constructor used when passing options (generated by scaffolding
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    // DbSets 
    public virtual DbSet<Booking> Bookings { get; set; }
    public virtual DbSet<Event> Events { get; set; }
    public virtual DbSet<Venue> Venues { get; set; }

    
    // OnModelCreating method was generated automatically by scaffolding
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951AEDF80FBC2C");

            entity.HasOne(d => d.Event).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__EventI__4D94879B");

            entity.HasOne(d => d.Venue).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__VenueI__4E88ABD4");
        });

       
        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Events__7944C81057FB4DEF");
        });

        modelBuilder.Entity<Venue>(entity =>
        {
            entity.HasKey(e => e.VenueId).HasName("PK__Venues__3C57E5F28B9B7167");
        });

        OnModelCreatingPartial(modelBuilder);
    }


    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
